project:
  type: website

website:
  title: "quarto_website_compute_render_locally_quarto_publish"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



